name: ci

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create .env file
        run: |
          touch .env
          echo "RESAS_API_KEY=${{ secrets.RESAS_API_KEY }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run format

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          RESAS_API_KEY: ${{ secrets.RESAS_API_KEY }}
