name: e2e tests

on:
  - pull_request

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create .env file
        run: |
          touch .env
          echo "RESAS_API_KEY=${{ secrets.RESAS_API_KEY }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
